-- =========================================================
-- EMPLOYEES TABLE
-- Main employee/user directory for WorkTime
-- =========================================================

CREATE TABLE IF NOT EXISTS public.employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id TEXT UNIQUE,

    employee_code TEXT UNIQUE,

    full_name TEXT NOT NULL,

    email TEXT,

    phone TEXT,

    department TEXT,

    position TEXT,

    system_role TEXT NOT NULL DEFAULT 'Employee',

    status TEXT NOT NULL DEFAULT 'Active',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================
-- INDEXES
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_employees_user_id
    ON public.employees(user_id);

CREATE INDEX IF NOT EXISTS idx_employees_system_role
    ON public.employees(system_role);

CREATE INDEX IF NOT EXISTS idx_employees_status
    ON public.employees(status);

-- =========================================================
-- COMMENTS
-- =========================================================

COMMENT ON TABLE public.employees
IS 'Main employee directory for the WorkTime system';

COMMENT ON COLUMN public.employees.user_id
IS 'Application/auth user identifier';

COMMENT ON COLUMN public.employees.system_role
IS 'System role such as Admin or Employee';

COMMENT ON COLUMN public.employees.status
IS 'Employee account status such as Active or Inactive';
